"""Deterministic financial calculations used by the Stock Research Terminal.

Financial numbers are never generated by an LLM here. Functions in this module
accept already-fetched statement/fact data and return calculated metrics.
"""

from __future__ import annotations

import math
from typing import Any

import pandas as pd


def _number(value: Any) -> float | None:
    try:
        if value is None or pd.isna(value):
            return None
        value = float(value)
        return value if math.isfinite(value) else None
    except (TypeError, ValueError):
        return None


def _annual_rows(df: pd.DataFrame | None) -> pd.DataFrame:
    if df is None or df.empty:
        return pd.DataFrame()

    rows = df.copy()
    if "form" in rows.columns:
        rows = rows[rows["form"].isin(["10-K", "20-F"])]
    if "fp" in rows.columns:
        rows = rows[rows["fp"].eq("FY")]

    if rows.empty:
        return rows

    if "fy" in rows.columns:
        rows["_fy_num"] = pd.to_numeric(rows["fy"], errors="coerce")
        rows = rows.dropna(subset=["_fy_num"])
        if rows.empty:
            return rows
        sort_cols = ["_fy_num"]
        ascending = [False]
        if "filed" in rows.columns:
            sort_cols.append("filed")
            ascending.append(False)
        rows = rows.sort_values(sort_cols, ascending=ascending)
        rows = rows.drop_duplicates("_fy_num", keep="first")
        rows = rows.sort_values("_fy_num", ascending=False)
    elif "filed" in rows.columns:
        rows = rows.sort_values("filed", ascending=False)

    return rows.reset_index(drop=True)


def annual_values(df: pd.DataFrame | None) -> dict[int, float]:
    """Return one value per fiscal year, preferring the most recently filed fact."""
    rows = _annual_rows(df)
    if rows.empty or "fy" not in rows.columns or "val" not in rows.columns:
        return {}

    out: dict[int, float] = {}
    for _, row in rows.iterrows():
        try:
            year = int(row["fy"])
        except (TypeError, ValueError):
            continue
        value = _number(row["val"])
        if value is not None and year not in out:
            out[year] = value
    return out


def latest_annual(df: pd.DataFrame | None) -> tuple[int, float, dict[str, Any]] | None:
    rows = _annual_rows(df)
    if rows.empty or "fy" not in rows.columns or "val" not in rows.columns:
        return None
    row = rows.iloc[0]
    try:
        year = int(row["fy"])
    except (TypeError, ValueError):
        return None
    value = _number(row["val"])
    if value is None:
        return None
    return year, value, row.to_dict()


def cagr_from_series(values: dict[int, float], years: int = 3) -> float | None:
    if years <= 0 or not values:
        return None
    ordered = sorted(values)
    if len(ordered) < years + 1:
        return None
    end_year = ordered[-1]
    start_candidates = [y for y in ordered if y <= end_year - years]
    if not start_candidates:
        return None
    start_year = max(start_candidates)
    start = _number(values.get(start_year))
    end = _number(values.get(end_year))
    if start is None or end is None or start <= 0 or end <= 0:
        return None
    return (end / start) ** (1 / (end_year - start_year)) - 1


def pct_change(current: float | None, prior: float | None) -> float | None:
    current = _number(current)
    prior = _number(prior)
    if current is None or prior is None or prior == 0:
        return None
    return current / prior - 1


def ratio(numerator: float | None, denominator: float | None) -> float | None:
    numerator = _number(numerator)
    denominator = _number(denominator)
    if numerator is None or denominator is None or denominator == 0:
        return None
    return numerator / denominator


def _combine_series(*series_maps: dict[int, float]) -> dict[int, float]:
    years = sorted(set().union(*(m.keys() for m in series_maps if m)))
    return {
        year: sum(m[year] for m in series_maps if year in m)
        for year in years
        if any(year in m for m in series_maps)
    }


def build_sec_financial_quality(snapshot: dict[str, pd.DataFrame]) -> dict[str, Any]:
    """Build auditable quality metrics from SEC annual facts only."""
    revenue = annual_values(snapshot.get("Revenue"))
    gross_profit = annual_values(snapshot.get("Gross Profit"))
    operating_income = annual_values(snapshot.get("Operating Income"))
    net_income = annual_values(snapshot.get("Net Income"))
    operating_cf = annual_values(snapshot.get("Operating Cash Flow"))
    capex = annual_values(snapshot.get("Capital Expenditure"))
    assets = annual_values(snapshot.get("Assets"))
    liabilities = annual_values(snapshot.get("Liabilities"))
    cash = annual_values(snapshot.get("Cash"))
    debt_current = annual_values(snapshot.get("Debt Current"))
    debt_noncurrent = annual_values(snapshot.get("Debt Noncurrent"))
    diluted_shares = annual_values(snapshot.get("Diluted Shares"))

    debt = _combine_series(debt_current, debt_noncurrent)
    # Do not assume missing CapEx is zero. FCF is only calculated when both
    # operating cash flow and CapEx are available for the same fiscal year.
    free_cash_flow = {
        year: operating_cf[year] - abs(capex[year])
        for year in sorted(set(operating_cf) & set(capex))
    }

    latest: dict[str, Any] = {}

    latest_revenue = revenue.get(max(revenue)) if revenue else None
    latest_net_income = net_income.get(max(net_income)) if net_income else None

    if latest_revenue is not None:
        latest["revenue"] = latest_revenue
    if latest_net_income is not None:
        latest["net_income"] = latest_net_income

    latest_year = max(revenue) if revenue else None
    if latest_year is not None:
        latest["fiscal_year"] = latest_year
        latest["gross_margin"] = ratio(gross_profit.get(latest_year), revenue.get(latest_year))
        latest["operating_margin"] = ratio(operating_income.get(latest_year), revenue.get(latest_year))
        latest["net_margin"] = ratio(net_income.get(latest_year), revenue.get(latest_year))
        latest["fcf_margin"] = ratio(free_cash_flow.get(latest_year), revenue.get(latest_year))

    if latest_year is not None and latest_net_income is not None and latest_year in assets:
        latest["roa_simple"] = ratio(
            latest_net_income,
            assets.get(latest_year),
        )

    latest["revenue_cagr_3y"] = cagr_from_series(revenue, 3)
    latest["net_income_cagr_3y"] = cagr_from_series(net_income, 3)
    latest["fcf_cagr_3y"] = cagr_from_series(free_cash_flow, 3)

    if debt:
        latest_debt_year = max(debt)
        latest["debt"] = debt[latest_debt_year]
    if cash:
        latest["cash"] = cash[max(cash)]
    if liabilities:
        latest["liabilities"] = liabilities[max(liabilities)]

    if debt and cash and max(debt) == max(cash):
        latest["net_debt"] = debt[max(debt)] - cash[max(cash)]

    if len(debt) >= 2:
        years = sorted(debt)
        latest["debt_change_yoy"] = pct_change(debt[years[-1]], debt[years[-2]])

    share_growth = None
    if len(diluted_shares) >= 2:
        years = sorted(diluted_shares)
        share_growth = pct_change(diluted_shares[years[-1]], diluted_shares[years[-2]])
    latest["diluted_shares_yoy"] = share_growth

    trend_years = sorted(set(revenue) | set(net_income) | set(free_cash_flow), reverse=True)[:5]
    trend = []
    for year in sorted(trend_years):
        trend.append(
            {
                "FY": year,
                "Revenue": revenue.get(year),
                "Net Income": net_income.get(year),
                "Operating Cash Flow": operating_cf.get(year),
                "CapEx": capex.get(year),
                "Free Cash Flow": free_cash_flow.get(year),
                "Gross Margin": ratio(gross_profit.get(year), revenue.get(year)),
                "Operating Margin": ratio(operating_income.get(year), revenue.get(year)),
                "Net Margin": ratio(net_income.get(year), revenue.get(year)),
            }
        )

    return {
        "latest": latest,
        "series": {
            "Revenue": revenue,
            "Net Income": net_income,
            "Operating Cash Flow": operating_cf,
            "Capital Expenditure": capex,
            "Free Cash Flow": free_cash_flow,
            "Assets": assets,
            "Liabilities": liabilities,
            "Cash": cash,
            "Debt": debt,
            "Diluted Shares": diluted_shares,
        },
        "trend": trend,
    }
